#!/usr/bin/env bash
# scripts/new_workshop.sh
#
# Generate a docker-compose override file for a new workshop slot.
#
# Usage:
#   ./scripts/new_workshop.sh <name> <offset>
#
# Examples:
#   ./scripts/new_workshop.sh workshopB 10   # ports 8010-8013, obs-app 3001
#   ./scripts/new_workshop.sh workshopC 20   # ports 8020-8023, obs-app 3002
#
# Workshop A (base) uses offset 0 (orchestrator=8000, coder=8001, ...)
# Each new workshop uses offset = +10 from the previous one.
#
# The generated file is written to:
#   docker-compose.workshop-<name>.yml
# (<name> is normalized to lowercase — Docker image refs must be lowercase.)
#
# NOTE: Services that publish host ports (orchestrator, coder, reviewer, qa,
# obs-app) are inlined below instead of using `extends`. Docker Compose merges
# `ports` from `extends` with the parent service, so child port overrides were
# ignored and workshop B re-bound 8000/3000 (same as workshop A).

set -euo pipefail

# ── Argument validation ────────────────────────────────────────────────────────
if [[ $# -ne 2 ]]; then
  echo "Usage: $0 <name> <offset>" >&2
  echo "Example: $0 workshopB 10" >&2
  exit 1
fi

NAME="$1"
OFFSET="$2"

# Compose builds image names from project + service names; OCI requires lowercase.
NAME_LOWER=$(printf '%s' "$NAME" | tr '[:upper:]' '[:lower:]')
if [[ "$NAME" != "$NAME_LOWER" ]]; then
  echo "Note: normalizing workshop name '$NAME' -> '$NAME_LOWER' (Docker requires lowercase image names)." >&2
fi
NAME="$NAME_LOWER"

# Validate offset is a non-negative integer
if ! [[ "$OFFSET" =~ ^[0-9]+$ ]]; then
  echo "Error: offset must be a non-negative integer, got: $OFFSET" >&2
  exit 1
fi

if [[ "$OFFSET" -eq 0 ]]; then
  echo "Error: offset 0 is reserved for Workshop A (the base docker-compose.yml)" >&2
  exit 1
fi

# ── Port calculations ──────────────────────────────────────────────────────────
BASE_ORCHESTRATOR=8000
BASE_CODER=8001
BASE_REVIEWER=8002
BASE_QA=8003
BASE_OBS=3000

PORT_ORCHESTRATOR=$(( BASE_ORCHESTRATOR + OFFSET ))
PORT_CODER=$(( BASE_CODER + OFFSET ))
PORT_REVIEWER=$(( BASE_REVIEWER + OFFSET ))
PORT_QA=$(( BASE_QA + OFFSET ))
PORT_OBS=$(( BASE_OBS + OFFSET / 10 ))   # obs-app: 3000 + (offset/10)

# ── Output file ───────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUTPUT_FILE="${REPO_ROOT}/docker-compose.workshop-${NAME}.yml"

if [[ -f "$OUTPUT_FILE" ]]; then
  echo "Warning: ${OUTPUT_FILE} already exists — overwriting." >&2
fi

# ── Generate override file ─────────────────────────────────────────────────────
cat > "$OUTPUT_FILE" <<EOF
# Auto-generated by scripts/new_workshop.sh for workshop: ${NAME}
# Offset: ${OFFSET}
# Ports: orchestrator=${PORT_ORCHESTRATOR}, coder=${PORT_CODER},
#        reviewer=${PORT_REVIEWER}, qa=${PORT_QA}, obs-app=${PORT_OBS}
#
# Usage:
#   docker compose -f docker-compose.yml -f $(basename "$OUTPUT_FILE") up -d

# Workshop-specific network (isolated from other workshops)
networks:
  mawf-net-${NAME}:
    driver: bridge

# Workshop-specific volumes
volumes:
  artifacts-${NAME}:
  pg-data-${NAME}:
  redis-data-${NAME}:

services:
  postgres-${NAME}:
    extends:
      file: docker-compose.yml
      service: postgres
    volumes:
      - pg-data-${NAME}:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d:ro
    networks:
      - mawf-net-${NAME}
    # No ports: binding

  redis-${NAME}:
    extends:
      file: docker-compose.yml
      service: redis
    volumes:
      - redis-data-${NAME}:/data
    networks:
      - mawf-net-${NAME}
    # No ports: binding

  # ── Inlined (no extends): port-publishing services ─────────────────────────
  # See NOTE at top of scripts/new_workshop.sh — extends + ports merge bug.

  coder-${NAME}:
    build:
      context: .
      dockerfile: services/coder/Dockerfile
    ports:
      - "${PORT_CODER}:8001"
    environment:
      ANTHROPIC_API_KEY: \${ANTHROPIC_API_KEY}
      REDIS_URL: redis://:\${REDIS_PASSWORD}@redis-${NAME}:6379/0
      DATABASE_URL: postgresql://\${POSTGRES_USER:-mawf}:\${POSTGRES_PASSWORD}@postgres-${NAME}:5432/\${POSTGRES_DB:-mawf}
      ARTIFACT_PATH: /artifacts
      INPUT_PATH: /input
    volumes:
      - artifacts-${NAME}:/artifacts
      - ./input:/input:ro
    networks:
      - mawf-net-${NAME}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
    depends_on:
      postgres-${NAME}:
        condition: service_healthy
      redis-${NAME}:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8001/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 40s

  reviewer-${NAME}:
    build:
      context: .
      dockerfile: services/reviewer/Dockerfile
    ports:
      - "${PORT_REVIEWER}:8002"
    environment:
      ANTHROPIC_API_KEY: \${ANTHROPIC_API_KEY}
      REDIS_URL: redis://:\${REDIS_PASSWORD}@redis-${NAME}:6379/0
      DATABASE_URL: postgresql://\${POSTGRES_USER:-mawf}:\${POSTGRES_PASSWORD}@postgres-${NAME}:5432/\${POSTGRES_DB:-mawf}
      ARTIFACT_PATH: /artifacts
      INPUT_PATH: /input
    volumes:
      - artifacts-${NAME}:/artifacts
      - ./input:/input:ro
    networks:
      - mawf-net-${NAME}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
    depends_on:
      postgres-${NAME}:
        condition: service_healthy
      redis-${NAME}:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8002/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 40s

  qa-${NAME}:
    build:
      context: .
      dockerfile: services/qa/Dockerfile
    ports:
      - "${PORT_QA}:8003"
    environment:
      ANTHROPIC_API_KEY: \${ANTHROPIC_API_KEY}
      REDIS_URL: redis://:\${REDIS_PASSWORD}@redis-${NAME}:6379/0
      DATABASE_URL: postgresql://\${POSTGRES_USER:-mawf}:\${POSTGRES_PASSWORD}@postgres-${NAME}:5432/\${POSTGRES_DB:-mawf}
      ARTIFACT_PATH: /artifacts
      INPUT_PATH: /input
    volumes:
      - artifacts-${NAME}:/artifacts
      - ./input:/input:ro
    networks:
      - mawf-net-${NAME}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
    depends_on:
      postgres-${NAME}:
        condition: service_healthy
      redis-${NAME}:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8003/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 40s

  orchestrator-${NAME}:
    build:
      context: .
      dockerfile: services/orchestrator/Dockerfile
    ports:
      - "${PORT_ORCHESTRATOR}:8000"
    environment:
      ANTHROPIC_API_KEY: \${ANTHROPIC_API_KEY}
      REDIS_URL: redis://:\${REDIS_PASSWORD}@redis-${NAME}:6379/0
      DATABASE_URL: postgresql://\${POSTGRES_USER:-mawf}:\${POSTGRES_PASSWORD}@postgres-${NAME}:5432/\${POSTGRES_DB:-mawf}
      ARTIFACT_PATH: /artifacts
      INPUT_PATH: /input
      CODER_URL: http://coder-${NAME}:8001
      REVIEWER_URL: http://reviewer-${NAME}:8002
      QA_URL: http://qa-${NAME}:8003
      SME_DATA_URL: http://sme-data-${NAME}:8080
      SME_API_URL: http://sme-api-${NAME}:8080
      SME_UX_URL: http://sme-ux-${NAME}:8080
      SME_BUSINESS_URL: http://sme-business-${NAME}:8080
      SME_NETWORKING_URL: http://sme-networking-${NAME}:8080
      SME_DEVOPS_URL: http://sme-devops-${NAME}:8080
    volumes:
      - artifacts-${NAME}:/artifacts
      - ./input:/input:ro
    networks:
      - mawf-net-${NAME}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
    depends_on:
      postgres-${NAME}:
        condition: service_healthy
      redis-${NAME}:
        condition: service_healthy
      coder-${NAME}:
        condition: service_healthy
      reviewer-${NAME}:
        condition: service_healthy
      qa-${NAME}:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 40s

  sme-data-${NAME}:
    extends:
      file: docker-compose.yml
      service: sme-data
    environment:
      DATABASE_URL: postgresql://\${POSTGRES_USER:-mawf}:\${POSTGRES_PASSWORD}@postgres-${NAME}:5432/\${POSTGRES_DB:-mawf}
      REDIS_URL: redis://:\${REDIS_PASSWORD}@redis-${NAME}:6379/0
    networks:
      - mawf-net-${NAME}
    depends_on:
      postgres-${NAME}:
        condition: service_healthy
      redis-${NAME}:
        condition: service_healthy

  sme-api-${NAME}:
    extends:
      file: docker-compose.yml
      service: sme-api
    environment:
      DATABASE_URL: postgresql://\${POSTGRES_USER:-mawf}:\${POSTGRES_PASSWORD}@postgres-${NAME}:5432/\${POSTGRES_DB:-mawf}
      REDIS_URL: redis://:\${REDIS_PASSWORD}@redis-${NAME}:6379/0
    networks:
      - mawf-net-${NAME}
    depends_on:
      postgres-${NAME}:
        condition: service_healthy
      redis-${NAME}:
        condition: service_healthy

  sme-ux-${NAME}:
    extends:
      file: docker-compose.yml
      service: sme-ux
    environment:
      DATABASE_URL: postgresql://\${POSTGRES_USER:-mawf}:\${POSTGRES_PASSWORD}@postgres-${NAME}:5432/\${POSTGRES_DB:-mawf}
      REDIS_URL: redis://:\${REDIS_PASSWORD}@redis-${NAME}:6379/0
    networks:
      - mawf-net-${NAME}
    depends_on:
      postgres-${NAME}:
        condition: service_healthy
      redis-${NAME}:
        condition: service_healthy

  sme-business-${NAME}:
    extends:
      file: docker-compose.yml
      service: sme-business
    environment:
      DATABASE_URL: postgresql://\${POSTGRES_USER:-mawf}:\${POSTGRES_PASSWORD}@postgres-${NAME}:5432/\${POSTGRES_DB:-mawf}
      REDIS_URL: redis://:\${REDIS_PASSWORD}@redis-${NAME}:6379/0
    networks:
      - mawf-net-${NAME}
    depends_on:
      postgres-${NAME}:
        condition: service_healthy
      redis-${NAME}:
        condition: service_healthy

  sme-networking-${NAME}:
    extends:
      file: docker-compose.yml
      service: sme-networking
    environment:
      DATABASE_URL: postgresql://\${POSTGRES_USER:-mawf}:\${POSTGRES_PASSWORD}@postgres-${NAME}:5432/\${POSTGRES_DB:-mawf}
      REDIS_URL: redis://:\${REDIS_PASSWORD}@redis-${NAME}:6379/0
    networks:
      - mawf-net-${NAME}
    depends_on:
      postgres-${NAME}:
        condition: service_healthy
      redis-${NAME}:
        condition: service_healthy

  sme-devops-${NAME}:
    extends:
      file: docker-compose.yml
      service: sme-devops
    environment:
      DATABASE_URL: postgresql://\${POSTGRES_USER:-mawf}:\${POSTGRES_PASSWORD}@postgres-${NAME}:5432/\${POSTGRES_DB:-mawf}
      REDIS_URL: redis://:\${REDIS_PASSWORD}@redis-${NAME}:6379/0
    networks:
      - mawf-net-${NAME}
    depends_on:
      postgres-${NAME}:
        condition: service_healthy
      redis-${NAME}:
        condition: service_healthy

  obs-app-${NAME}:
    build:
      context: ./obs-app
      dockerfile: Dockerfile
    ports:
      - "${PORT_OBS}:3000"
    environment:
      NEXT_PUBLIC_ORCHESTRATOR_URL: http://localhost:${PORT_ORCHESTRATOR}
      NEXT_PUBLIC_WS_URL: ws://localhost:${PORT_ORCHESTRATOR}
      ORCHESTRATOR_INTERNAL_URL: http://orchestrator-${NAME}:8000
    networks:
      - mawf-net-${NAME}
    restart: unless-stopped
    depends_on:
      - orchestrator-${NAME}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
EOF

chmod +x "$OUTPUT_FILE" 2>/dev/null || true

echo "Generated: ${OUTPUT_FILE}"
echo ""
echo "Workshop '${NAME}' port assignments:"
echo "  orchestrator : ${PORT_ORCHESTRATOR}"
echo "  coder        : ${PORT_CODER}"
echo "  reviewer     : ${PORT_REVIEWER}"
echo "  qa           : ${PORT_QA}"
echo "  obs-app      : ${PORT_OBS}"
echo ""
echo "To start workshop ${NAME}:"
echo "  docker compose -f docker-compose.yml -f $(basename "$OUTPUT_FILE") up -d"
